env:
  browser: true
  es2021: true
  jest/globals: true
extends: google
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  indent: ["error", 4],
  quotes: ["error", "double"],
  max-len: ["error", 160, ignoreComments: true],
  require-jsdoc: ["error", "require": {
            "FunctionDeclaration": false,
            "MethodDefinition": false,
            "ClassDeclaration": false,
            "ArrowFunctionExpression": false,
            "FunctionExpression": false
        }],
  space-infix-ops: ["error", int32Hint: true ],
}
